// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMDATrM5w3dG6xO4GcOI78S-iui35SllY',
    appId: '1:266192011481:web:0074c66190d80f8afe3ec8',
    messagingSenderId: '266192011481',
    projectId: 'e-sahayta-demo',
    authDomain: 'e-sahayta-demo.firebaseapp.com',
    storageBucket: 'e-sahayta-demo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAclSoSUklGZM6-DFD4ZNUSeKBAz6GQ7Qk',
    appId: '1:710548783999:android:49eb8101a9187530c5904a',
    messagingSenderId: '710548783999',
    projectId: 'e-sahayta-app',
    storageBucket: 'e-sahayta-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUWo-Ci-hHAu9AAXS6pmgCT9uQiAH1e-Y',
    appId: '1:266192011481:ios:ead39b3f6ade1d91fe3ec8',
    messagingSenderId: '266192011481',
    projectId: 'e-sahayta-demo',
    storageBucket: 'e-sahayta-demo.firebasestorage.app',
    iosBundleId: 'com.example.eSahayta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUWo-Ci-hHAu9AAXS6pmgCT9uQiAH1e-Y',
    appId: '1:266192011481:ios:ead39b3f6ade1d91fe3ec8',
    messagingSenderId: '266192011481',
    projectId: 'e-sahayta-demo',
    storageBucket: 'e-sahayta-demo.firebasestorage.app',
    iosBundleId: 'com.example.eSahayta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMDATrM5w3dG6xO4GcOI78S-iui35SllY',
    appId: '1:266192011481:web:2a5af112680b1f8efe3ec8',
    messagingSenderId: '266192011481',
    projectId: 'e-sahayta-demo',
    authDomain: 'e-sahayta-demo.firebaseapp.com',
    storageBucket: 'e-sahayta-demo.firebasestorage.app',
  );
}
